/**
 * File generated by Magnet Magnet Lang Tool on Apr 5, 2016 4:54:27 PM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.mmx.client.internal.poll;

import retrofit.http.*;
import retrofit.MagnetCall;

public interface ServerSettingsService {

  /**
   * 
   * PUT /com.magnet.server/settings/user
   * @param body style:Body optional:false
   * @param callback asynchronous callback
   */
  @PUT("com.magnet.server/settings/user")
  MagnetCall<java.util.Map<String, String>> updateSettings(
     @Body java.util.Map<String, String> body,
     retrofit.Callback<java.util.Map<String, String>> callback
  );

}
