/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

import com.magnet.max.android.UserProfile;
import com.magnet.mmx.util.GsonData;

public class BasicUserInfo {

  private static final String USER_PROFILE_JSON = "{\"userIdentifier\":\"%s\", \"mDisplayName\":\"%s\"}";
  
  private String userId;

  
  private String displayName;

  public String getUserId() {
    return userId;
  }

  public String getDisplayName() {
    return displayName;
  }

  public UserProfile toUserProfile() {
    //TODO : better way to construct a UserProfile
    String json = String.format(USER_PROFILE_JSON, userId, displayName);
    return GsonData.getGson().fromJson(json, UserProfile.class);
  }

  /**
  * Builder for UserInfo
  **/
  public static class UserInfoBuilder {
    private BasicUserInfo toBuild = new BasicUserInfo();

    public UserInfoBuilder() {
    }

    public BasicUserInfo build() {
      return toBuild;
    }

    public UserInfoBuilder userId(String value) {
      toBuild.userId = value;
      return this;
    }

    public UserInfoBuilder displayName(String value) {
      toBuild.displayName = value;
      return this;
    }
  }
}
