/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class ChannelSummaryResponse {

  private String channelName;

  private int publishedItemCount;

  private String lastPublishedTime;
  
  private Integer subscriberCount;

  
  private java.util.List<UserInfo> subscribers;

  
  private java.util.List<PubSubItemChannel> messages;

  public Integer getSubscriberCount() {
    return subscriberCount;
  }

  public java.util.List<UserInfo> getSubscribers() {
    return subscribers;
  }

  public java.util.List<PubSubItemChannel> getMessages() {
    return messages;
  }

  public String getChannelName() {
    return channelName;
  }

  public int getPublishedItemCount() {
    return publishedItemCount;
  }

  public String getLastPublishedTime() {
    return lastPublishedTime;
  }

}
