/**
 * File generated by Magnet Magnet Lang Tool on Dec 17, 2015 2:24:58 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

import com.google.gson.annotations.SerializedName;

/**
 * The key to look up channel summary
 */
public class ChannelLookupKey {

  private String channelName;

  private Boolean privateChannel;

  @SerializedName("userId")
  private String ownerId;

  /**
   *
   * @param channelName
   * @param isPublic
   * @param ownerId
   */
  public ChannelLookupKey(String channelName, Boolean isPublic, String ownerId) {
    this.channelName = channelName;
    this.privateChannel = !isPublic;
    this.ownerId = ownerId;
  }

  public String getChannelName() {
    return channelName;
  }

  public Boolean isPublicChannel() {
    return !privateChannel;
  }

  public String getOwnerId() {
    return ownerId;
  }
}
