/**
 * File generated by Magnet Magnet Lang Tool on Dec 17, 2015 2:24:58 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class ChannelLookupKey {

  private String channelName;

  private Boolean privateChannel;

  public ChannelLookupKey(String channelName, Boolean privateChannel) {
    this.channelName = channelName;
    this.privateChannel = privateChannel;
  }

  public String getChannelName() {
    return channelName;
  }

  public Boolean getPrivateChannel() {
    return privateChannel;
  }


}
