/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

import com.magnet.mmx.client.api.ChannelDetail;
import com.magnet.mmx.client.api.MMXChannel;

public class ChannelSummaryResponse {

  private String channelName;

  private int publishedItemCount;

  private String lastPublishedTime;
  
  private Integer subscriberCount;

  
  private java.util.List<BasicUserInfo> subscribers;

  
  private java.util.List<PubSubItem> messages;

  public Integer getSubscriberCount() {
    return subscriberCount;
  }

  public java.util.List<BasicUserInfo> getSubscribers() {
    return subscribers;
  }

  public java.util.List<PubSubItem> getMessages() {
    return messages;
  }

  public String getChannelName() {
    return channelName;
  }

  public int getPublishedItemCount() {
    return publishedItemCount;
  }

  public String getLastPublishedTime() {
    return lastPublishedTime;
  }

  public ChannelDetail toChannelDetail(MMXChannel channel) {
    //return new ChannelDetail.Builder().channel(channel).messages(messages).subscribers()
    return null;
  }

}
