/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class ChannelSummaryRequest {

  private Boolean includeOwnerInfo;

  
  private Integer numOfMessages;


  private java.util.List<ChannelLookupKey> channelIds;

  
  private Long messagesSince;

  
  private Integer numOfSubcribers;

  public Boolean getIncludeOwnerInfo() {
    return includeOwnerInfo;
  }

  public Integer getNumOfMessages() {
    return numOfMessages;
  }

  public java.util.List<ChannelLookupKey> getChannelIds() {
    return channelIds;
  }

  public Long getMessagesSince() {
    return messagesSince;
  }

  public Integer getNumOfSubcribers() {
    return numOfSubcribers;
  }


  /**
  * Builder for ChannelSummaryRequest
  **/
  public static class Builder {
    private ChannelSummaryRequest toBuild = new ChannelSummaryRequest();

    public Builder() {
    }

    public ChannelSummaryRequest build() {
      return toBuild;
    }

    public Builder includeOwnerInfo(Boolean value) {
      toBuild.includeOwnerInfo = value;
      return this;
    }

    public Builder numOfMessages(Integer value) {
      toBuild.numOfMessages = value;
      return this;
    }

    public Builder channelIds(java.util.List<ChannelLookupKey> value) {
      toBuild.channelIds = value;
      return this;
    }

    public Builder messagesSince(Long value) {
      toBuild.messagesSince = value;
      return this;
    }

    public Builder numOfSubcribers(Integer value) {
      toBuild.numOfSubcribers = value;
      return this;
    }
  }
}
