/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class ChannelSummaryResponse {

  
  
  private Integer subscriberCount;

  
  private java.util.List<UserInfo> subscribers;

  
  private java.util.List<PubSubItemChannel> messages;

  public Integer getSubscriberCount() {
    return subscriberCount;
  }

  public java.util.List<UserInfo> getSubscribers() {
    return subscribers;
  }

  public java.util.List<PubSubItemChannel> getMessages() {
    return messages;
  }


  /**
  * Builder for ChannelSummaryResponse
  **/
  public static class ChannelSummaryResponseBuilder {
    private ChannelSummaryResponse toBuild = new ChannelSummaryResponse();

    public ChannelSummaryResponseBuilder() {
    }

    public ChannelSummaryResponse build() {
      return toBuild;
    }

    public ChannelSummaryResponseBuilder subscriberCount(Integer value) {
      toBuild.subscriberCount = value;
      return this;
    }

    public ChannelSummaryResponseBuilder subscribers(java.util.List<UserInfo> value) {
      toBuild.subscribers = value;
      return this;
    }

    public ChannelSummaryResponseBuilder messages(java.util.List<PubSubItemChannel> value) {
      toBuild.messages = value;
      return this;
    }
  }
}
