/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class ItemPublisher {

  
  
  private String userId;

  
  private String deviceId;

  public String getUserId() {
    return userId;
  }

  public String getDeviceId() {
    return deviceId;
  }


  /**
  * Builder for ItemPublisher
  **/
  public static class ItemPublisherBuilder {
    private ItemPublisher toBuild = new ItemPublisher();

    public ItemPublisherBuilder() {
    }

    public ItemPublisher build() {
      return toBuild;
    }

    public ItemPublisherBuilder userId(String value) {
      toBuild.userId = value;
      return this;
    }

    public ItemPublisherBuilder deviceId(String value) {
      toBuild.deviceId = value;
      return this;
    }
  }
}
