/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class PubSubItem {

  
  
  private java.util.Map<String, String> content;

  
  private String channelName;

  
  //private UserInfo publisherInfo;

  
  private String itemId;

  
  private PubSubPayload metaData;

  
  private ItemPublisher publisher;

  public java.util.Map<String, String> getContent() {
    return content;
  }

  public String getChannelName() {
    return channelName;
  }

  //public UserInfo getPublisherInfo() {
  //  return publisherInfo;
  //}

  public String getItemId() {
    return itemId;
  }

  public PubSubPayload getMetaData() {
    return metaData;
  }

  public ItemPublisher getPublisher() {
    return publisher;
  }

  /**
  * Builder for PubSubItemChannel
  **/
  public static class PubSubItemBuilder {
    private PubSubItem toBuild = new PubSubItem();

    public PubSubItemBuilder() {
    }

    public PubSubItem build() {
      return toBuild;
    }

    public PubSubItemBuilder content(java.util.Map<String, String> value) {
      toBuild.content = value;
      return this;
    }

    public PubSubItemBuilder channelName(String value) {
      toBuild.channelName = value;
      return this;
    }

    //public PubSubItemBuilder publisherInfo(UserInfo value) {
    //  toBuild.publisherInfo = value;
    //  return this;
    //}

    public PubSubItemBuilder itemId(String value) {
      toBuild.itemId = value;
      return this;
    }

    public PubSubItemBuilder metaData(PubSubPayload value) {
      toBuild.metaData = value;
      return this;
    }

    public PubSubItemBuilder publisher(ItemPublisher value) {
      toBuild.publisher = value;
      return this;
    }
  }
}
