/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class PubSubItemChannel {

  
  
  private java.util.Map<String, String> content;

  
  private String channelName;

  
  private UserInfo publisherInfo;

  
  private String itemId;

  
  private PubSubPayload metaData;

  
  private ItemPublisher publisher;

  public java.util.Map<String, String> getContent() {
    return content;
  }

  public String getChannelName() {
    return channelName;
  }

  public UserInfo getPublisherInfo() {
    return publisherInfo;
  }

  public String getItemId() {
    return itemId;
  }

  public PubSubPayload getMetaData() {
    return metaData;
  }

  public ItemPublisher getPublisher() {
    return publisher;
  }


  /**
  * Builder for PubSubItemChannel
  **/
  public static class PubSubItemChannelBuilder {
    private PubSubItemChannel toBuild = new PubSubItemChannel();

    public PubSubItemChannelBuilder() {
    }

    public PubSubItemChannel build() {
      return toBuild;
    }

    public PubSubItemChannelBuilder content(java.util.Map<String, String> value) {
      toBuild.content = value;
      return this;
    }

    public PubSubItemChannelBuilder channelName(String value) {
      toBuild.channelName = value;
      return this;
    }

    public PubSubItemChannelBuilder publisherInfo(UserInfo value) {
      toBuild.publisherInfo = value;
      return this;
    }

    public PubSubItemChannelBuilder itemId(String value) {
      toBuild.itemId = value;
      return this;
    }

    public PubSubItemChannelBuilder metaData(PubSubPayload value) {
      toBuild.metaData = value;
      return this;
    }

    public PubSubItemChannelBuilder publisher(ItemPublisher value) {
      toBuild.publisher = value;
      return this;
    }
  }
}
