/**
 * File generated by Magnet Magnet Lang Tool on Apr 19, 2016 4:49:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class PubSubPayload {

  
  
  private String creationDate;

  
  private String data;

  
  private String mtype;

  public String getCreationDate() {
    return creationDate;
  }

  public String getData() {
    return data;
  }

  public String getMtype() {
    return mtype;
  }


  /**
  * Builder for PubSubPayload
  **/
  public static class PubSubPayloadBuilder {
    private PubSubPayload toBuild = new PubSubPayload();

    public PubSubPayloadBuilder() {
    }

    public PubSubPayload build() {
      return toBuild;
    }

    public PubSubPayloadBuilder creationDate(String value) {
      toBuild.creationDate = value;
      return this;
    }

    public PubSubPayloadBuilder data(String value) {
      toBuild.data = value;
      return this;
    }

    public PubSubPayloadBuilder mtype(String value) {
      toBuild.mtype = value;
      return this;
    }
  }
}
