/**
 * File generated by Magnet Magnet Lang Tool on Dec 16, 2015 1:47:30 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.channel;

public class UserInfo {

  
  
  private String userId;

  
  private String displayName;

  public String getUserId() {
    return userId;
  }

  public String getDisplayName() {
    return displayName;
  }


  /**
  * Builder for UserInfo
  **/
  public static class UserInfoBuilder {
    private UserInfo toBuild = new UserInfo();

    public UserInfoBuilder() {
    }

    public UserInfo build() {
      return toBuild;
    }

    public UserInfoBuilder userId(String value) {
      toBuild.userId = value;
      return this;
    }

    public UserInfoBuilder displayName(String value) {
      toBuild.displayName = value;
      return this;
    }
  }
}
