/**
 * File generated by Magnet Magnet Lang Tool on Apr 11, 2016 1:09:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.survey.model;

public class SendMessageResponse {

  
  
  private java.util.List<String> unsentList;

  
  private Count count;

  
  private java.util.List<SentList> sentList;

  public java.util.List<String> getUnsentList() {
    return unsentList;
  }

  public Count getCount() {
    return count;
  }

  public java.util.List<SentList> getSentList() {
    return sentList;
  }


  /**
  * Builder for SendMessageResponse
  **/
  public static class SendMessageResponseBuilder {
    private SendMessageResponse toBuild = new SendMessageResponse();

    public SendMessageResponseBuilder() {
    }

    public SendMessageResponse build() {
      return toBuild;
    }

    public SendMessageResponseBuilder unsentList(java.util.List<String> value) {
      toBuild.unsentList = value;
      return this;
    }

    public SendMessageResponseBuilder count(Count value) {
      toBuild.count = value;
      return this;
    }

    public SendMessageResponseBuilder sentList(java.util.List<SentList> value) {
      toBuild.sentList = value;
      return this;
    }
  }
}
