/**
 * File generated by Magnet Magnet Lang Tool on Apr 11, 2016 1:09:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.survey.model;

public class SurveyAnswer {

  
  
  private String responseId;

  
  private String text;

  
  private String questionId;

  
  private String selectedOptionId;

  
  private String answerId;

  public String getResponseId() {
    return responseId;
  }

  public String getText() {
    return text;
  }

  public String getQuestionId() {
    return questionId;
  }

  public String getSelectedOptionId() {
    return selectedOptionId;
  }

  public String getAnswerId() {
    return answerId;
  }


  /**
  * Builder for SurveyAnswer
  **/
  public static class SurveyAnswerBuilder {
    private SurveyAnswer toBuild = new SurveyAnswer();

    public SurveyAnswerBuilder() {
    }

    public SurveyAnswer build() {
      return toBuild;
    }

    public SurveyAnswerBuilder responseId(String value) {
      toBuild.responseId = value;
      return this;
    }

    public SurveyAnswerBuilder text(String value) {
      toBuild.text = value;
      return this;
    }

    public SurveyAnswerBuilder questionId(String value) {
      toBuild.questionId = value;
      return this;
    }

    public SurveyAnswerBuilder selectedOptionId(String value) {
      toBuild.selectedOptionId = value;
      return this;
    }

    public SurveyAnswerBuilder answerId(String value) {
      toBuild.answerId = value;
      return this;
    }
  }
}
