/**
 * File generated by Magnet Magnet Lang Tool on Apr 11, 2016 1:09:57 PM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.mmx.client.internal.survey.model;

public enum SurveyType {
  CHECKLIST,
  POLL,
  SURVEY
};
