/**
 * File generated by Magnet Magnet Lang Tool on Apr 11, 2016 1:09:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.survey.model;

public class SurveyOption {

  
  
  private String optionId;

  
  private String value;

  
  private Integer displayOrder;

  public String getOptionId() {
    return optionId;
  }

  public String getValue() {
    return value;
  }

  public Integer getDisplayOrder() {
    return displayOrder;
  }


  /**
  * Builder for SurveyOption
  **/
  public static class SurveyOptionBuilder {
    private SurveyOption toBuild = new SurveyOption();

    public SurveyOptionBuilder() {
    }

    public SurveyOption build() {
      return toBuild;
    }

    public SurveyOptionBuilder optionId(String value) {
      toBuild.optionId = value;
      return this;
    }

    public SurveyOptionBuilder value(String value) {
      toBuild.value = value;
      return this;
    }

    public SurveyOptionBuilder displayOrder(Integer value) {
      toBuild.displayOrder = value;
      return this;
    }
  }
}
