/**
 * File generated by Magnet Magnet Lang Tool on Apr 5, 2016 4:54:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.poll.model;

public class Count {

  
  
  private Integer requested;

  
  private Integer sent;

  
  private Integer unsent;

  public Integer getRequested() {
    return requested;
  }

  public Integer getSent() {
    return sent;
  }

  public Integer getUnsent() {
    return unsent;
  }


  /**
  * Builder for Count
  **/
  public static class CountBuilder {
    private Count toBuild = new Count();

    public CountBuilder() {
    }

    public Count build() {
      return toBuild;
    }

    public CountBuilder requested(Integer value) {
      toBuild.requested = value;
      return this;
    }

    public CountBuilder sent(Integer value) {
      toBuild.sent = value;
      return this;
    }

    public CountBuilder unsent(Integer value) {
      toBuild.unsent = value;
      return this;
    }
  }
}
