/**
 * File generated by Magnet Magnet Lang Tool on Apr 5, 2016 4:54:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.poll.model;

public class SurveyOption {

  
  
  private String optionId;

  
  private Integer displayOder;

  
  private String value;

  public String getOptionId() {
    return optionId;
  }

  public Integer getDisplayOder() {
    return displayOder;
  }

  public String getValue() {
    return value;
  }


  /**
  * Builder for SurveyOption
  **/
  public static class SurveyOptionBuilder {
    private SurveyOption toBuild = new SurveyOption();

    public SurveyOptionBuilder() {
    }

    public SurveyOption build() {
      return toBuild;
    }

    public SurveyOptionBuilder optionId(String value) {
      toBuild.optionId = value;
      return this;
    }

    public SurveyOptionBuilder displayOder(Integer value) {
      toBuild.displayOder = value;
      return this;
    }

    public SurveyOptionBuilder value(String value) {
      toBuild.value = value;
      return this;
    }
  }
}
