/**
 * File generated by Magnet Magnet Lang Tool on Apr 5, 2016 4:54:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.poll.model;

public class Survey {

  
  
  private String id;

  
  private SurveyDefinition surveyDefinition;

  
  private java.util.List<String> owners;

  
  private java.util.Map<String, String> metaData;

  public String getId() {
    return id;
  }

  public SurveyDefinition getSurveyDefinition() {
    return surveyDefinition;
  }

  public java.util.List<String> getOwners() {
    return owners;
  }

  public java.util.Map<String, String> getMetaData() {
    return metaData;
  }


  /**
  * Builder for Survey
  **/
  public static class SurveyBuilder {
    private Survey toBuild = new Survey();

    public SurveyBuilder() {
    }

    public Survey build() {
      return toBuild;
    }

    public SurveyBuilder id(String value) {
      toBuild.id = value;
      return this;
    }

    public SurveyBuilder surveyDefinition(SurveyDefinition value) {
      toBuild.surveyDefinition = value;
      return this;
    }

    public SurveyBuilder owners(java.util.List<String> value) {
      toBuild.owners = value;
      return this;
    }

    public SurveyBuilder metaData(java.util.Map<String, String> value) {
      toBuild.metaData = value;
      return this;
    }
  }
}
