/**
 * File generated by Magnet Magnet Lang Tool on Apr 11, 2016 1:09:57 PM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.mmx.client.internal.poll.model;

public enum SurveyParticipantModel {
  PRIVATE,
  PUBLIC
};
