/**
 * File generated by Magnet Magnet Lang Tool on Apr 11, 2016 1:09:57 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.poll.model;

public class SurveyResults {

  
  
  private java.util.List<SurveyChoiceResult> summary;

  
  private java.util.List<SurveyAnswer> myAnswers;

  
  private Survey survey;

  public java.util.List<SurveyChoiceResult> getSummary() {
    return summary;
  }

  public java.util.List<SurveyAnswer> getMyAnswers() {
    return myAnswers;
  }

  public Survey getSurvey() {
    return survey;
  }


  /**
  * Builder for SurveyResults
  **/
  public static class SurveyResultsBuilder {
    private SurveyResults toBuild = new SurveyResults();

    public SurveyResultsBuilder() {
    }

    public SurveyResults build() {
      return toBuild;
    }

    public SurveyResultsBuilder summary(java.util.List<SurveyChoiceResult> value) {
      toBuild.summary = value;
      return this;
    }

    public SurveyResultsBuilder myAnswers(java.util.List<SurveyAnswer> value) {
      toBuild.myAnswers = value;
      return this;
    }

    public SurveyResultsBuilder survey(Survey value) {
      toBuild.survey = value;
      return this;
    }
  }
}
