/**
 * File generated by Magnet Magnet Lang Tool on Apr 5, 2016 4:54:27 PM
 * @see {@link http://developer.magnet.com}
 */
package com.magnet.mmx.client.internal.poll.model;

public enum SurveyParticipantModel {
  PRIVATE,
  PUBLIC
};
