/**
 * File generated by Magnet Magnet Lang Tool on Apr 5, 2016 4:54:27 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magnet.mmx.client.internal.poll.model;

public class SurveyDefinition {

  
  
  private java.util.Date startDate;

  
  private SurveyParticipantModel participantModel;

  
  private java.util.List<SurveyQuestion> questions;

  
  private java.util.Date endDate;

  
  private SurveyParticipantModel resultAccessModel;

  
  private SurveyType type;

  
  private String notificationChannelId;

  public java.util.Date getStartDate() {
    return startDate;
  }

  public SurveyParticipantModel getParticipantModel() {
    return participantModel;
  }

  public java.util.List<SurveyQuestion> getQuestions() {
    return questions;
  }

  public java.util.Date getEndDate() {
    return endDate;
  }

  public SurveyParticipantModel getResultAccessModel() {
    return resultAccessModel;
  }

  public SurveyType getType() {
    return type;
  }

  public String getNotificationChannelId() {
    return notificationChannelId;
  }


  /**
  * Builder for SurveyDefinition
  **/
  public static class SurveyDefinitionBuilder {
    private SurveyDefinition toBuild = new SurveyDefinition();

    public SurveyDefinitionBuilder() {
    }

    public SurveyDefinition build() {
      return toBuild;
    }

    public SurveyDefinitionBuilder startDate(java.util.Date value) {
      toBuild.startDate = value;
      return this;
    }

    public SurveyDefinitionBuilder participantModel(SurveyParticipantModel value) {
      toBuild.participantModel = value;
      return this;
    }

    public SurveyDefinitionBuilder questions(java.util.List<SurveyQuestion> value) {
      toBuild.questions = value;
      return this;
    }

    public SurveyDefinitionBuilder endDate(java.util.Date value) {
      toBuild.endDate = value;
      return this;
    }

    public SurveyDefinitionBuilder resultAccessModel(SurveyParticipantModel value) {
      toBuild.resultAccessModel = value;
      return this;
    }

    public SurveyDefinitionBuilder type(SurveyType value) {
      toBuild.type = value;
      return this;
    }

    public SurveyDefinitionBuilder notificationChannelId(String value) {
      toBuild.notificationChannelId = value;
      return this;
    }
  }
}
